version: '3.8'

services:
  # Serveur Web PHP
  php-app:
    build: .
    container_name: boudi-php-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
      - mongo-db

  # Base de données SQL
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boudi_sql
    ports:
      - "3306:3306"

  # Base de données NoSQL
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"