services:
  # Serveur Web PHP (Apache)
  php-app:
    build: .
    container_name: boudi-php-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
      - mongo-db
    networks:
      - boudi-network

  # Base de données SQL (MySQL)
  mysql-db:
    image: mysql:8.0
    container_name: boudi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boudi_sql
    ports:
      - "3306:3306"
    networks:
      - boudi-network

  # Base de données NoSQL (MongoDB)
  mongo-db:
    image: mongo:latest
    container_name: boudi-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - boudi-network

networks:
  boudi-network:
    driver: bridge